parse_config:
  # Custom behaviors and their display forms
  # keymap-drawer will automatically parse custom behaviors if they are properly defined
  # in your .dtsi files, but we can provide hints about special ones
  
  # Sticky label for one-shot/sticky keys
  sticky_label: "⏱"
  
  # Transparent key styling - use just "▽" in YAML
  trans_legend:
    t: "▽"
    type: trans
  
  # Simple mappings for tap-dance behaviors
  raw_binding_map:
    # Shorthand aliases for common keys
    "▽": {t: "▽", type: trans}  # Transparent key shorthand
    "&bt_0": "BT 0"
    "&bt_1": "BT 1"
    "&bt_2": "BT 2"
    "&bt_3": "BT 3"
    "&caps_shift": "Shift/Caps"
    "&caps_return": "Enter/Caps"
  
  # Define layer names if display-name doesn't work
  layer_names:
    - BASE
    - DEV
    - NPAD
    - SYSTEM
    - MOUSE
    - NAV

draw_config:
  # Optional: Customize appearance
  key_w: 60
  key_h: 56
  split_gap: 30
  combo_w: 24
  combo_h: 20
  
  # Font sizes
  inner_pad_w: 2
  inner_pad_h: 2
  outer_pad_w: 20
  outer_pad_h: 20
  
  # Legend sizes
  glyph_tap_size: 14
  glyph_hold_size: 12
  glyph_shifted_size: 10
